from rblxopencloud import *
import dotenv
import time
import os

file_path = input("File path: ")


if dotenv.get_variable(".env","RBLX_USER_ID") != 1234 and dotenv.get_variable(".env","RBLX_API_KEY") != "replaceable":
    creator = User(
       dotenv.get_variable(".env","RBLX_USER_ID"),dotenv.get_variable(".env","RBLX_API_KEY")
    )
        
    asset_name = input("Asset name: ")
    asset_description = input("Asset description: ")
    asset_price = input("Asset price (Robux), leave empty if you dont want it onsale: ")


    asset_price_1 = asset_price
    asset_name_1 = asset_name
    asset_description_1 = asset_description

    if asset_price_1 == "" and asset_name_1 == "" and asset_description_1 == "":
        with open(file_path, 'rb') as file:
                creator.upload_asset(file, AssetType.Decal, "Decal", "Automatically generated by 'Roblox-decal-creator'.")
                print("You can check your inventory or creator dashboard at your decals, you can rename them however you want. =)")
    elif asset_price_1 == "" and asset_name_1 != "" and asset_description_1 != "":
         with open(file_path, 'rb') as file:
                creator.upload_asset(file, AssetType.Decal, asset_name_1, asset_description_1)
                print("You can check your inventory or creator dashboard at your decals, you can rename them however you want. =)")
    elif asset_price_1 != "" and asset_name != "" and asset_description_1 == "":
         with open(file_path, 'rb') as file:
                creator.upload_asset(file, AssetType.Decal, asset_name_1 ,"Automatically generated by 'Roblox-decal-creator'.", asset_price_1)
                print("You can check your inventory or creator dashboard at your decals, you can rename them however you want. =)")
    elif asset_price_1 != "" and asset_name != "" and asset_description_1 != "":
         with open(file_path, 'rb') as file:
                creator.upload_asset(file, AssetType.Decal, asset_name_1, asset_description_1, asset_price_1)
                print("You can check your inventory or creator dashboard at your decals, you can rename them however you want. =)")



    with open(file_path, 'rb') as file:
        creator.upload_asset(file, AssetType.Decal, "Decal", "Automatically generated by 'Roblox-decal-creator'.")
        print("You can check your inventory or creator dashboard at your decals, you can rename them however you want. =)")
else:
    api_key = input("Your Api key: ")
    user_id = input("Your User Id: ")
    dotenv.set_variable(".env","RBLX_USER_ID",user_id)
    dotenv.set_variable(".env","RBLX_API_KEY",api_key)
    print("The program needs to restart, restarting in 5 secs")
    time.sleep(5)
    os.system("python index.py")
    exit(0)
    










